#ifndef _DS_INMP441_H_
#define _DS_INMP441_H_


#define I2S_MIC_NUM I2S_NUM_0
#define I2S_MIC_SAMPLE_RATE 44100
#define I2S_MIC_BITS_PER_SAMPLE I2S_BITS_PER_SAMPLE_16BIT
#define I2S_MIC_CHANNEL_FORMAT I2S_CHANNEL_FMT_ONLY_LEFT
void i2s_mic_init();
#endif
